name: Flutter Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true
          cache-key: "flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}"

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Navigate to frontend directory
        run: cd Appifyours/frontend && pwd && ls -la

      - name: Install dependencies
        run: |
          cd Appifyours/frontend
          flutter pub get

      - name: Analyze code (optional)
        run: |
          cd Appifyours/frontend
          flutter analyze || true
        continue-on-error: true

      - name: Make gradlew executable
        run: chmod +x Appifyours/frontend/android/gradlew

      - name: Run tests (optional)
        run: |
          cd Appifyours/frontend
          flutter test --coverage || echo "Tests completed with warnings"
        continue-on-error: true

      - name: Build APK (debug)
        run: |
          cd Appifyours/frontend
          flutter build apk --debug --no-shrink

      - name: Build APK (release)
        run: |
          cd Appifyours/frontend
          flutter build apk --release

      - name: Build AAB (release)
        run: |
          cd Appifyours/frontend
          flutter build appbundle --release

      - name: List build outputs
        run: |
          echo "Debug APK:"
          ls -lh Appifyours/frontend/build/app/outputs/flutter-apk/ || true
          echo "Release outputs:"
          ls -lh Appifyours/frontend/build/app/outputs/bundle/release/ || true

      - name: Upload APK (debug)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: Appifyours/frontend/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: warn

      - name: Upload APK (release)
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: Appifyours/frontend/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: warn

      - name: Upload AAB (release)
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: Appifyours/frontend/build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: warn
